#!/bin/bash

# DefaultKeyBinding.dict can't be symlinked, so copy it to ~/Library/KeyBindings whenever a commit is made that modifies it
# https://apple.stackexchange.com/a/224074
if [[ $(git diff --cached --name-only | grep 'DefaultKeyBinding.dict' | wc -l) -eq 1 ]];
then
   bdir=$(git rev-parse --show-toplevel)
   ldir=~/Library/KeyBindings

   cp $bdir/DefaultKeyBinding.dict $ldir/DefaultKeyBinding.dict
   printf "Copied updated DefaultKeyBinding.dict to %s\n" $ldir
fi
