% Page formatting
\LoadClass[11pt]{article}
\usepackage[margin=1in]{geometry}

% Theorem definitions
% Italicize non-remark theorem environments
\usepackage{amsthm}
\theoremstyle{plain}
\newtheorem{assump}{Assumption}
\newtheorem{claim}{Claim}
\newtheorem{conj}{Conjecture}
\newtheorem{corollary}{Corollary}
\newtheorem{lemma}{Lemma}
\newtheorem{prop}{Proposition}
\newtheorem{theorem}{Theorem}
\theoremstyle{definition}
\newtheorem{remark}{Remark}

% Load mystyle.sty
\usepackage{mystyle}
